import { useEffect, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { Mail, Phone, Plus, Search, UserRound } from "lucide-react";
import { toast } from "sonner";
import { AppShell } from "@/components/app/AppShell";
import { EmptyState, PageHeader } from "@/components/app/PageHeader";
import { Button } from "@/components/ui/button";import { Input } from "@/components/ui/input";import { Label } from "@/components/ui/label";import { Textarea } from "@/components/ui/textarea";import { Dialog,DialogContent,DialogFooter,DialogHeader,DialogTitle,DialogTrigger } from "@/components/ui/dialog";
import { createClient,listClients,type DbClient } from "@/lib/live-data";
export const Route=createFileRoute("/clientes")({component:ClientsPage});
function ClientsPage(){const [query,setQuery]=useState("");const [items,setItems]=useState<DbClient[]>([]);const [open,setOpen]=useState(false);const load=()=>listClients().then(setItems).catch(e=>toast.error(e.message));useEffect(load,[]);const list=items.filter(c=>`${c.name} ${c.document||""} ${c.contact_name||""}`.toLowerCase().includes(query.toLowerCase()));return <AppShell title="Clientes"><PageHeader title="Clientes" subtitle={`${items.length} clientes cadastrados`} actions={<NewClientDialog open={open} setOpen={setOpen} onSaved={load}/>}/><div className="surface-panel p-4"><div className="relative"><Search className="absolute top-1/2 left-3 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar cliente" className="h-11 pl-9"/></div></div>{list.length===0?<EmptyState title="Nenhum cliente" description="Cadastre o primeiro cliente para começar as locações." action={<Button variant="hero" onClick={()=>setOpen(true)}><Plus className="h-4 w-4"/> Novo Cliente</Button>}/>:<div className="grid gap-3 lg:grid-cols-2">{list.map(c=><article key={c.id} className="surface-panel p-4"><div className="flex gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-primary/12"><UserRound className="h-5 w-5"/></span><div className="min-w-0"><h2 className="truncate text-sm font-bold">{c.name}</h2><p className="text-xs text-muted-foreground">{c.document||"Sem documento"}</p></div></div><div className="mt-4 grid gap-2 text-xs text-muted-foreground sm:grid-cols-2"><span className="flex gap-2"><Phone className="h-3.5 w-3.5"/>{c.phone||"—"}</span><span className="flex gap-2"><Mail className="h-3.5 w-3.5"/>{c.email||"—"}</span><span>Responsável: {c.contact_name||"—"}</span></div>{c.notes&&<p className="mt-3 rounded-lg bg-secondary/50 p-2.5 text-xs text-muted-foreground">{c.notes}</p>}</article>)}</div>}</AppShell>}
function NewClientDialog({open,setOpen,onSaved}:{open:boolean;setOpen:(v:boolean)=>void;onSaved:()=>void}){const [f,setF]=useState<any>({type:"company",name:"",document:"",phone:"",email:"",contact_name:"",notes:""});const [busy,setBusy]=useState(false);async function save(){if(!f.name)return;setBusy(true);try{await createClient({...f,document:f.document||null,phone:f.phone||null,email:f.email||null,contact_name:f.contact_name||null,notes:f.notes||null});toast.success("Cliente salvo");setOpen(false);setF({type:"company",name:"",document:"",phone:"",email:"",contact_name:"",notes:""});onSaved();}catch(e){toast.error(e instanceof Error?e.message:"Erro ao salvar")}finally{setBusy(false)}}return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button variant="hero"><Plus className="h-4 w-4"/> Novo Cliente</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Novo cliente</DialogTitle></DialogHeader><div className="grid gap-3 sm:grid-cols-2"><Field label="Nome / Razão social" value={f.name} set={(v)=>setF({...f,name:v})} wide/><Field label="CPF / CNPJ" value={f.document} set={(v)=>setF({...f,document:v})}/><Field label="Telefone" value={f.phone} set={(v)=>setF({...f,phone:v})}/><Field label="E-mail" value={f.email} set={(v)=>setF({...f,email:v})} wide/><Field label="Responsável" value={f.contact_name} set={(v)=>setF({...f,contact_name:v})} wide/><div className="space-y-1.5 sm:col-span-2"><Label>Observações</Label><Textarea value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/></div></div><DialogFooter><Button variant="hero" onClick={save} disabled={busy}>{busy?"Salvando...":"Salvar cliente"}</Button></DialogFooter></DialogContent></Dialog>}
function Field({label,value,set,wide}:{label:string;value:string;set:(v:string)=>void;wide?:boolean}){return <div className={`space-y-1.5 ${wide?"sm:col-span-2":""}`}><Label>{label}</Label><Input value={value} onChange={e=>set(e.target.value)} className="h-11"/></div>}
