/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as RadiosRouteImport } from './routes/radios'
import { Route as RadiosRadioIdRouteImport } from './routes/radios.$radioId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RadiosRoute = RadiosRouteImport.update({
  id: '/radios',
  path: '/radios',
  getParentRoute: () => rootRouteImport,
} as any)
const RadiosRadioIdRoute = RadiosRadioIdRouteImport.update({
  id: '/$radioId',
  path: '/$radioId',
  getParentRoute: () => RadiosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/radios': typeof RadiosRouteWithChildren
  '/radios/$radioId': typeof RadiosRadioIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/radios': typeof RadiosRouteWithChildren
  '/radios/$radioId': typeof RadiosRadioIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/radios': typeof RadiosRouteWithChildren
  '/radios/$radioId': typeof RadiosRadioIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/radios' | '/radios/$radioId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/radios' | '/radios/$radioId'
  id: '__root__' | '/' | '/dashboard' | '/radios' | '/radios/$radioId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  RadiosRoute: typeof RadiosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radios': {
      id: '/radios'
      path: '/radios'
      fullPath: '/radios'
      preLoaderRoute: typeof RadiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radios/$radioId': {
      id: '/radios/$radioId'
      path: '/$radioId'
      fullPath: '/radios/$radioId'
      preLoaderRoute: typeof RadiosRadioIdRouteImport
      parentRoute: typeof RadiosRoute
    }
  }
}

interface RadiosRouteChildren {
  RadiosRadioIdRoute: typeof RadiosRadioIdRoute
}

const RadiosRouteChildren: RadiosRouteChildren = {
  RadiosRadioIdRoute: RadiosRadioIdRoute,
}

const RadiosRouteWithChildren =
  RadiosRoute._addFileChildren(RadiosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  RadiosRoute: RadiosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
